/* autogenerated by Processing revision 1293 on 2024-10-03 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import ddf.minim.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_240929a extends PApplet {


PImage bg;
Minim minim;
AudioPlayer player;

public void setup() {
  /* size commented out by preprocessor */;
  minim = new Minim(this);

  // 背景画像をロード
  bg = loadImage("loli.png");

  // 音声ファイルをロード
  player = minim.loadFile("hateyou.mp3", 1024);
  player.play();
}

public void draw() {
  // 背景画像を描画
  image(bg, 0, 0, width, height);

  // 波形を描画
  stroke(255);
  for (int i = 0; i < player.bufferSize() - 1; i++) {
    float x1 = map(i, 0, player.bufferSize(), 0, width);
    float x2 = map(i+1, 0, player.bufferSize(), 0, width);
    line(x1, height/2 + player.left.get(i) * 50, x2, height/2 + player.left.get(i+1) * 60);
  }

  // リズムに合わせて動く円
  float amplitude = 0;
  for (int i = 0; i < player.bufferSize(); i++) {
    amplitude += abs(player.left.get(i));
  }
  amplitude /= player.bufferSize();
  float size = map(amplitude, 0, 0.5f, 50, 200);
  
  fill(255, 100);
  noStroke();
  ellipse(width/2, height/2, size, size);
}

public void stop() {
  player.close();
  minim.stop();
  super.stop();
}


  public void settings() { size(1200, 600); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sketch_240929a" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
